spring:
  config:
    activate:
      on-profile: prod


  datasource:
    url: jdbc:postgresql://prod-db-host:5432/iamdb
    username: iam_user
    password: prodpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate   # don't auto-update in prod

temporal:
  host: temporal-prod-host
  port: 7233
