name: Build and Deploy Cyrev API to Azure Container Apps

on:
  push:
    branches:
      - main
    paths:
      - "cyrev-apis/**"
      - "common/**"
      - "pom.xml"

env:
  AZURE_CONTAINER_REGISTRY: cyrevregistry.azurecr.io
  IMAGE_NAME: cyrev-service
  RESOURCE_GROUP: CyRev
  CONTAINER_APP_NAME: cyrev-service
  TEMPORAL_HOST: temporal
  TEMPORAL_PORT: 7233
  SPRING_PROFILES_ACTIVE: prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check Temporal secret length
        env:
          TEMPORAL_ADDRESS: ${{ secrets.TEMPORAL_ADDRESS }}
          TEMPORAL_NAMESPACE: ${{ secrets.TEMPORAL_NAMESPACE }}
          TEMPORAL_API_KEY: ${{ secrets.TEMPORAL_API_KEY }}
        run: |
          echo "TEMPORAL_ADDRESS length: ${#TEMPORAL_ADDRESS}"
          echo "TEMPORAL_NAMESPACE length: ${#TEMPORAL_NAMESPACE}"
          echo "TEMPORAL_API_KEY length: ${#TEMPORAL_API_KEY}"

      - name: Build Spring Boot app
        run: mvn clean package -pl cyrev-apis -am -DskipTests

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: az acr login --name cyrevregistry

      - name: Build Docker image
        run: |
          docker build \
            -f cyrev-apis/Dockerfile \
            -t $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:${{ github.sha }} \
            -t $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:latest \
            .

      - name: Push Docker image
        run: |
          docker push $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:${{ github.sha }}
          docker push $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:latest

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name $CONTAINER_APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --image $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:${{ github.sha }} \
            --set-env-vars \
              SPRING_DATASOURCE_URL=${{ secrets.DB_URL }} \
              TEMPORAL_API_KEY=${{ secrets.TEMPORAL_API_KEY }} \
              TEMPORAL_NAMESPACE=${{ secrets.TEMPORAL_NAMESPACE }} \
              TEMPORAL_ADDRESS=${{ secrets.TEMPORAL_ADDRESS }} \
              TEMPORAL_HOST=temporal \
              TEMPORAL_PORT=7233 \
